// Industry trigger engine: for each Indian industry, what tends to cause rallies and
// sell-offs, which metrics to watch, and how sensitive it is to measurable macro factors.
//
//   Event -> Industry -> Trigger bucket -> Direction -> Horizon
//
// `macro` maps a factor key (see FACTORS in context.js) to +1 (factor up = good for the
// industry) or -1 (factor up = bad). Rates are proxied by the US 10Y yield (^TNX); USD/INR
// up means a weaker rupee.

/* ---------- master trigger buckets (used to classify headlines) ---------- */

export const BUCKETS = {
  demand: { label: "Demand / volumes", tier: "quarterly", re: /\bdemand\b|volume growth|offtake|footfall|traffic|occupancy|bookings|sales (rise|jump|grow|fall|drop|decline)|registrations|dispatches|despatches/i },
  pricing: { label: "Pricing / realisations", tier: "quarterly", re: /price hike|raises? prices|hikes? prices|tariff hike|price cut|cuts? prices|realisation|realization|\barpu\b|\basp\b|prices? (rise|fall|jump|slump|surge|crash)/i },
  costs: { label: "Input costs", tier: "quarterly", re: /input cost|raw material|cost inflation|cost pressure|wage (hike|inflation)|freight (cost|rate)|fuel cost|power cost/i },
  margins: { label: "Margins", tier: "quarterly", re: /margin|ebitda|operating leverage|\bnim\b/i },
  capacity: { label: "Capacity / utilisation", tier: "cyclical", re: /capacity|utili[sz]ation|new plant|commission(ed|ing)?|shutdown|plant closure|expansion/i },
  competition: { label: "Competition", tier: "cyclical", re: /price war|competition|competitive intensity|discounting|dumping|cheap imports|anti-dumping/i },
  regulation: { label: "Regulation / policy", tier: "structural", re: /\bsebi\b|\brbi\b (norms|rules|curbs?|restrict|action|ban)|regulat|\bban\b|licen[cs]e|approval|usfda|warning letter|import alert|\bpli\b|subsid|\bgst\b|import duty|export duty|export ban|tariff|policy|trai|irdai|cerc|dgca|nclt|court|penalty|probe/i },
  rates: { label: "Interest rates", tier: "cyclical", re: /repo rate|rate cut|rate hike|interest rate|bond yield|g-?sec|monetary policy|\bmpc\b|\bfed\b|\bcrr\b|\bslr\b/i },
  currency: { label: "Currency", tier: "cyclical", re: /rupee|usd\/?inr|dollar index|\bforex\b|currency/i },
  commodities: { label: "Commodity prices", tier: "cyclical", re: /crude|oil price|brent|\bcoal\b|petcoke|steel price|iron ore|coking coal|aluminium|aluminum|copper|gold price|natural gas|\blng\b|palm oil|cotton|sugar price|rubber|lithium|tio2/i },
  govt_spending: { label: "Government spending", tier: "cyclical", re: /\bcapex\b|union budget|budget allocation|infrastructure (push|spend)|government (spend|order|capex)|\bnhai\b|railway (budget|capex)|defence (budget|procurement)|tender/i },
  orders: { label: "Orders / contracts", tier: "quarterly", re: /\border(s)?\b|order (book|inflow)|contract|\bbags?\b|letter of (award|intent)|\bl1\b/i },
  credit: { label: "Credit cycle / asset quality", tier: "cyclical", re: /credit growth|loan growth|\bnpa\b|gnpa|nnpa|asset quality|slippage|provision|credit cost|disbursement|collection efficiency|delinquen/i },
  liquidity: { label: "Liquidity / flows", tier: "sentiment", re: /\bfii|\bfpi|\bdii\b|inflow|outflow|block deal|bulk deal|\bmsci\b|\bftse\b|index (inclusion|rejig|rebalanc)|liquidity|mutual fund|\bsip\b/i },
  ai_theme: { label: "AI / data-centre theme", tier: "cyclical", re: /\bai\b|artificial intelligence|gen ?ai|data ?cent(er|re)|hyperscaler|nvidia|gpu|ai capex|ai bubble|ai (slowdown|spending|demand|trade)/i },
  technology: { label: "Technology / disruption", tier: "structural", re: /automation|\bcloud\b|digital|\bev\b|electric vehicle|disrupt|5g/i },
  inventory: { label: "Inventory cycle", tier: "cyclical", re: /inventor(y|ies)|destock|restock|channel (filling|stock)/i },
  balance_sheet: { label: "Balance sheet / funding", tier: "cyclical", re: /\bdebt\b|deleverag|leverage|credit rating|default|refinanc|fund ?rais|\bqip\b|rights issue|pledge/i },
  mna: { label: "M&A / consolidation", tier: "structural", re: /acqui|merger|amalgamat|demerg|stake (sale|buy)|takeover|open offer|joint venture|consolidat/i },
  earnings: { label: "Earnings / revisions", tier: "quarterly", re: /results?\b|\bq[1-4]\b|earnings|net profit|\bprofit\b|\bpat\b|beats? estimates|miss(es)? estimates|guidance|outlook/i },
  analyst: { label: "Broker calls / valuation", tier: "sentiment", re: /upgrade|downgrade|target price|re-?rat|de-?rat|valuation|outperform|underperform|\bbuy\b rating|\bsell\b rating/i },
  positioning: { label: "Positioning", tier: "sentiment", re: /short covering|profit booking|profit taking|upper circuit|lower circuit|f&o ban|crowded/i },
  macro_shock: { label: "Macro / geopolitical shock", tier: "cyclical", re: /\bwar\b|ukraine|russia|israel|iran|sanction|geopolit|strait|covid|pandemic|lockdown|recession|election|china|trump|tariffs on/i },
  monsoon: { label: "Monsoon / rural", tier: "cyclical", re: /monsoon|rainfall|kharif|rabi|\bcrop\b|rural (demand|income|wage)/i },
  inflation: { label: "Inflation", tier: "cyclical", re: /inflation|\bcpi\b|\bwpi\b/i },
  management: { label: "Management / governance", tier: "structural", re: /\bceo\b|\bcfo\b|\bmd\b|chairman|resign|appoint|steps down|auditor|fraud|governance|whistle/i },
};

export const TIERS = {
  structural: "Structural (5–10y)",
  cyclical: "Cyclical (1–3y)",
  quarterly: "Quarterly (1–4q)",
  sentiment: "Sentiment (immediate)",
};

const UP = /\b(surge[sd]?|jump(s|ed)?|soar(s|ed)?|rall(y|ies|ied)|gains?|rises?|rose|climbs?|record high|beats?|upgrade[sd]?|wins?|bags?|approv\w*|boost\w*|strong\w*|higher|outperform\w*|rate cuts?|cuts? (repo|rates?|interest)|tailwinds?|recover\w*)\b/i;
const DOWN = /\b(falls?|fell|drops?|dropped|plunge[sd]?|slump(s|ed)?|crash(es|ed)?|tank(s|ed)?|tumble[sd]?|slides?|declines?|cuts? (guidance|forecast|target)|miss(es|ed)?|downgrade[sd]?|bans?|banned|probe|penalty|warning|loss(es)?|weak\w*|lower|resign\w*|fraud|default\w*|headwinds?|sell-?off|rate hikes?|hikes? (repo|rates?|interest))\b/i;

/** Headline -> master trigger buckets + tone (+1 bullish, -1 bearish, 0 unclear). */
export function classifyTrigger(title) {
  const buckets = Object.entries(BUCKETS).filter(([, b]) => b.re.test(title)).map(([k]) => k);
  const up = UP.test(title), down = DOWN.test(title);
  return { buckets, tone: up && !down ? 1 : down && !up ? -1 : 0 };
}

/* ---------- industry playbooks ---------- */

const P = (name, match, macro, rally, selloff, metrics, newsQuery, ref = {}) => ({ name, match, macro, rally, selloff, metrics, newsQuery, ...ref });

export const PLAYBOOKS = {
  banks: P("Banks", /\bbank/i, { rates: -1 },
    ["RBI rate cuts / falling G-sec yields", "Credit growth acceleration (retail, corporate capex, housing, SME)", "Falling GNPA/NNPA, lower slippages & credit costs", "NIM expansion, CASA improvement, deposit repricing", "Lower CRR/SLR or risk weights", "Successful capital raise, strong CET1"],
    ["Deposit competition / NIM compression", "Rising NPAs, corporate stress, higher credit costs", "RBI tightening, liquidity shortage", "Deposit growth below loan growth", "Fraud / regulatory action, higher risk weights", "Bond-yield spike"],
    ["Credit growth", "NIM", "CASA", "GNPA / NNPA", "Credit cost", "Deposit growth"], "bank stocks", { index: { symbol: "^NSEBANK", name: "NIFTY Bank" } }),
  nbfc: P("NBFCs / housing finance", /credit services|consumer finance|mortgage|housing finance|nbfc|financial conglomerates|specialty finance/i, { rates: -1 },
    ["Falling interest rates / lower borrowing costs", "Strong AUM & loan growth", "Better collections, lower credit losses", "Rating upgrades, securitisation & funding access"],
    ["Funding costs rise / liquidity crisis (CP market stress)", "Asset-quality deterioration, higher provisioning", "RBI restrictions, ALM mismatch", "Wholesale-funding dependence"],
    ["AUM growth", "Cost of funds", "Spread", "GS3 / NS3", "Collection efficiency"], "NBFC stocks", { peers: ["BAJFINANCE.NS", "SHRIRAMFIN.NS", "CHOLAFIN.NS", "M&MFIN.NS", "LICHSGFIN.NS"] }),
  microfinance: P("Microfinance", /microfin|bandhan|creditaccess|spandana|fusion micro/i, { rates: -1 },
    ["Rural income recovery", "Collections improve", "Lower funding costs", "Government support"],
    ["Rural stress, political loan waivers", "Delinquencies / over-leveraging", "Regulatory restrictions"],
    ["Collection efficiency", "PAR 30+", "Disbursements"], "microfinance", { peers: ["BANDHANBNK.NS", "CREDITACC.NS", "SPANDANA.NS", "MANAPPURAM.NS"] }),
  insurance: P("Insurance", /insurance/i, { rates: -1 },
    ["Premium growth acceleration, rising penetration", "Better product mix / VNB margins", "Lower claims, better persistency", "Regulatory liberalisation, higher FDI limits"],
    ["Weak premium growth, high claims", "Pricing pressure / commoditisation", "Regulatory restrictions (surrender value, commissions)", "Falling persistency"],
    ["APE / GWP growth", "VNB margin", "Combined ratio", "Persistency"], "insurance stocks", { peers: ["HDFCLIFE.NS", "SBILIFE.NS", "ICICIPRULI.NS", "ICICIGI.NS"] }),
  capital_markets: P("AMCs / brokers / exchanges", /asset management|capital markets|financial data|stock exchange|exchange|broker/i, { smallcap: 1 },
    ["Equity markets rise, SIP flows increase", "Retail participation / new accounts", "New products, higher equity allocation"],
    ["Market correction, redemption surge", "SIP slowdown", "Fee / F&O regulation (SEBI)", "Passive shift, fee compression"],
    ["AUM", "SIP flows", "Market share", "F&O volumes"], "AMC broker stocks SEBI", { peers: ["HDFCAMC.NS", "CDSL.NS", "BSE.NS", "MCX.NS", "ANGELONE.NS"] }),
  it_services: P("IT services", /information technology services|it services|it consulting/i, { inr: 1, spx: 1, ai_dc: 1 },
    ["US/European IT budgets rise; cloud, AI, digital spend", "INR depreciation / strong USD", "Falling wage inflation & attrition, higher utilisation", "Large deal wins / TCV"],
    ["US recession / BFSI weakness, deal cancellations", "Pricing pressure", "INR appreciation, wage inflation", "AI cannibalising traditional services"],
    ["Revenue growth (cc)", "TCV / deal wins", "EBIT margin", "Attrition", "Utilisation"], "IT stocks", { index: { symbol: "^CNXIT", name: "NIFTY IT" } }),
  software: P("Software / SaaS", /software/i, { spx: 1, rates: -1, inr: 1, ai_dc: 1 },
    ["ARR growth, higher net retention", "AI monetisation", "Lower CAC, better gross margins"],
    ["Churn, longer sales cycles", "Enterprise budget cuts", "AI commoditisation", "Higher rates compress multiples"],
    ["ARR", "Net retention", "Gross margin"], "software stocks", { index: { symbol: "^CNXIT", name: "NIFTY IT" } }),
  telecom: P("Telecom", /telecom/i, { rates: -1 },
    ["Tariff hikes / ARPU increases", "Market consolidation, lower competition", "5G monetisation, lower capex intensity"],
    ["Price war, ARPU decline", "Spectrum costs, heavy capex", "AGR / regulatory liabilities"],
    ["ARPU", "Subscriber adds", "Capex / revenue"], "telecom tariff", { peers: ["BHARTIARTL.NS", "IDEA.NS", "TATACOMM.NS", "INDUSTOWER.NS"] }),
  oil_upstream: P("Oil & gas upstream", /oil & gas e&p|oil & gas integrated|oil & gas drilling|exploration/i, { crude: 1, gas: 1 },
    ["Crude / gas prices rise", "Production growth, exploration success", "Lower royalty / windfall tax"],
    ["Crude collapse, gas-price cuts", "Windfall taxes, production issues"],
    ["Brent", "Realisation / bbl", "Production"], "crude oil price ONGC", { peers: ["ONGC.NS", "OIL.NS", "RELIANCE.NS", "GAIL.NS"] }),
  refining: P("Refining & oil marketing", /refining|oil & gas refining|marketing/i, { crude: -1, inr: -1 },
    ["Higher refining (crack) spreads", "Stable or falling crude", "Government allows retail price pass-through", "Strong fuel demand"],
    ["Crude spike without retail price hikes", "Political price controls", "Crack spreads collapse / cheap Chinese exports", "Inventory losses"],
    ["GRM", "Marketing margin", "Brent"], "oil marketing companies crude", { peers: ["BPCL.NS", "IOC.NS", "HINDPETRO.NS", "RELIANCE.NS", "MRPL.NS"] }),
  gas: P("Gas distribution / utilities", /regulated gas|gas distribution|city gas|lng/i, { gas: -1, crude: 1 },
    ["Cheaper gas input (APM / LNG)", "CNG/PNG volume growth", "Higher crude makes CNG competitive"],
    ["Gas price spikes / APM cuts", "Regulatory margin caps, EV threat"],
    ["Volumes (mmscmd)", "EBITDA/scm"], "natural gas price CGD", { peers: ["IGL.NS", "MGL.NS", "GAIL.NS", "PETRONET.NS"] }),
  chemicals: P("Chemicals", /chemical/i, { crude: -1, inr: 1, china: -1 },
    ["China supply cuts / environmental shutdowns", "Import substitution, export demand", "Product price increases, lower feedstock", "Rupee depreciation"],
    ["Chinese dumping / global oversupply", "Capacity additions, destocking", "Feedstock inflation", "Product price collapse"],
    ["Product spreads", "Utilisation", "Export share"], "chemical stocks China", { peers: ["PIDILITIND.NS", "SRF.NS", "DEEPAKNTR.NS", "AARTIIND.NS", "NAVINFLUOR.NS"] }),
  paints: P("Paints", /paint|asian paints|berger|kansai|indigo/i, { crude: -1 },
    ["Crude / TiO2 prices fall", "Housing cycle, volume growth, premiumisation"],
    ["Crude spikes", "New capacity / price competition (new entrants)", "Housing slowdown"],
    ["Volume growth", "Gross margin"], "paint stocks crude", { peers: ["ASIANPAINT.NS", "BERGEPAINT.NS", "KANSAINER.NS", "INDIGOPNTS.NS"] }),
  fertilisers: P("Fertilisers / agrochem", /agricultural inputs|fertili|agrochem|pesticide/i, { gas: -1 },
    ["Good monsoon, higher acreage & crop prices", "Subsidy support / timely payments", "Lower gas & raw-material prices"],
    ["Poor monsoon", "Subsidy changes / price controls", "Input-cost inflation, Chinese dumping"],
    ["Monsoon", "Subsidy receivables", "Volumes"], "fertiliser monsoon subsidy", { peers: ["CHAMBLFERT.NS", "COROMANDEL.NS", "UPL.NS", "RCF.NS", "GSFC.NS"] }),
  steel: P("Steel", /steel/i, { steel: 1, china: 1 },
    ["Steel prices rise; China stimulus or production cuts", "Infrastructure spending", "Lower coking coal / iron ore", "Import tariffs / safeguard duty"],
    ["Chinese exports rise / China property crisis", "Steel prices fall, global recession", "Coking coal or iron ore spikes"],
    ["HRC price", "EBITDA/tonne", "Coking coal"], "steel prices", { peers: ["TATASTEEL.NS", "JSWSTEEL.NS", "SAIL.NS", "JINDALSTEL.NS"] }),
  aluminium: P("Aluminium", /aluminum|aluminium|hindalco|nalco|vedanta/i, { aluminium: 1 },
    ["LME aluminium rises; China constraints", "Alumina & power costs fall", "Energy-transition demand"],
    ["Aluminium price falls", "Alumina / power cost spikes", "Chinese exports"],
    ["LME aluminium", "Cost of production"], "aluminium prices", { peers: ["HINDALCO.NS", "NATIONALUM.NS", "VEDL.NS"] }),
  metals: P("Metals & mining", /copper|zinc|industrial metals|mining|silver|other precious/i, { copper: 1, china: 1 },
    ["Metal prices rise; China stimulus", "Supply disruptions"],
    ["Metal prices fall; China slowdown", "Royalty / export duty changes"],
    ["LME prices", "Volumes"], "metal prices", { peers: ["HINDALCO.NS", "VEDL.NS", "HINDZINC.NS", "NMDC.NS", "HINDCOPPER.NS"] }),
  coal: P("Coal / mining", /thermal coal|coal/i, { crude: 1 },
    ["Power demand / coal shortages", "E-auction premiums", "Higher energy prices"],
    ["Coal glut, lower e-auction prices", "Energy-transition worries"],
    ["Offtake", "E-auction premium"], "coal demand", { peers: ["COALINDIA.NS", "NLCINDIA.NS", "NMDC.NS"] }),
  cement: P("Cement", /building materials|cement/i, { rates: -1, crude: -1 },
    ["Cement price hikes, volume growth", "Infra & housing cycle", "Coal/petcoke & freight costs fall", "Utilisation up, consolidation"],
    ["Price war, capacity additions", "Coal/petcoke spike, freight inflation", "Weak construction / monsoon"],
    ["Cement price / bag", "EBITDA/tonne", "Utilisation", "Petcoke"], "cement prices", { peers: ["ULTRACEMCO.NS", "SHREECEM.NS", "AMBUJACEM.NS", "ACC.NS", "DALBHARAT.NS"] }),
  epc: P("Construction / EPC", /engineering & construction|construction|infrastructure operations|epc/i, { rates: -1 },
    ["Government capex: roads, railways, power, water, airports", "Order inflows (order-inflow / revenue up)", "Private capex revival"],
    ["Order delays / government spending cuts", "Working-capital stress, payment delays", "Commodity inflation, cost overruns"],
    ["Order inflow", "Order book / revenue", "Working capital days"], "infrastructure capex orders", { peers: ["LT.NS", "NCC.NS", "KEC.NS", "KPIL.NS", "PNCINFRA.NS"] }),
  capital_goods: P("Capital goods / engineering", /industrial machinery|electrical equipment|machinery|farm & heavy|tools & accessories|conglomerates|industrial distribution|pollution|metal fabrication/i, { rates: -1, copper: -1, steel: -1, ai_dc: 1 },
    ["Private & government capex, PLI, FDI", "Order-book acceleration", "Manufacturing PMI / capacity utilisation up", "Export orders, automation", "AI / data-centre power-equipment demand"],
    ["Capex postponements, high rates", "Order cancellations, weak IIP", "Commodity inflation", "China competition", "AI capex slowdown / data-centre order fears"],
    ["Order inflow / revenue", "Order book / revenue", "EBITDA margin"], "capital goods orders capex", { peers: ["LT.NS", "SIEMENS.NS", "ABB.NS", "BHEL.NS", "CUMMINSIND.NS", "THERMAX.NS"] }),
  power_gen: P("Power generation", /independent power|power producers|utilities - diversified|thermal power/i, { rates: -1, ai_dc: 1 },
    ["Power demand / peak demand growth, shortages", "Higher merchant tariffs", "Fuel costs fall, capacity additions"],
    ["Oversupply, merchant prices collapse", "Fuel shortages / coal costs rise", "PPA renegotiation"],
    ["PLF", "Merchant tariff", "Power demand"], "power demand", { peers: ["NTPC.NS", "TATAPOWER.NS", "NHPC.NS", "JSWENERGY.NS", "TORNTPOWER.NS"] }),
  transmission: P("Power transmission / regulated", /regulated electric|transmission|power grid/i, { rates: -1, ai_dc: 1 },
    ["Renewable additions, green corridors, grid expansion", "Data-centre demand, electrification", "Higher regulated returns"],
    ["Project delays, lower capex", "Regulatory disallowances, higher interest costs"],
    ["Capex", "Regulated equity", "Bids won"], "power transmission capex", { peers: ["POWERGRID.NS", "KEC.NS", "KPIL.NS", "SIEMENS.NS"] }),
  renewables: P("Renewable energy", /renewable|solar|wind/i, { rates: -1 },
    ["Lower module prices, lower rates", "Renewable auctions, corporate PPAs", "Storage economics improve, incentives"],
    ["Higher interest rates", "Module price inflation / import restrictions", "Policy uncertainty, grid constraints"],
    ["Capacity added", "Tariffs won", "Module prices"], "renewable energy solar", { peers: ["SUZLON.NS", "TATAPOWER.NS", "INOXWIND.NS", "NHPC.NS", "JSWENERGY.NS"] }),
  autos: P("Automobiles (PV / 2W / CV)", /auto manufacturers|automobile|motorcycle|tractor|truck manufacturers/i, { crude: -1, steel: -1, rates: -1 },
    ["Rate cuts / easy vehicle finance", "Rural recovery & good monsoon (2W, tractors)", "New launches, SUV demand, replacement cycle", "Infra & freight activity (CVs)", "Lower fuel / commodity prices"],
    ["Rate hikes, weak consumer confidence", "Commodity inflation", "EV disruption, regulatory costs", "Inventory build-up at dealers"],
    ["Monthly sales", "Dealer inventory", "Gross margin"], "auto sales", { peers: ["MARUTI.NS", "M&M.NS", "BAJAJ-AUTO.NS", "HEROMOTOCO.NS", "EICHERMOT.NS"] }),
  auto_components: P("Auto components", /auto parts|auto components|auto & truck/i, { steel: -1, aluminium: -1, inr: 1 },
    ["OEM production up, export growth", "New model wins, EV content, premiumisation", "Customer diversification"],
    ["OEM production cuts, customer concentration", "EV displacement of ICE parts", "Commodity inflation, pricing pressure"],
    ["OEM production", "Exports", "Content per vehicle"], "auto components", { peers: ["BOSCHLTD.NS", "MOTHERSON.NS", "BHARATFORG.NS", "EXIDEIND.NS", "ENDURANCE.NS"] }),
  tyres: P("Tyres", /tire|tyre|rubber/i, { crude: -1 },
    ["Natural rubber / crude fall", "Auto production & replacement demand", "Exports"],
    ["Rubber / crude spike", "OEM weakness, import competition"],
    ["Rubber price", "Replacement demand"], "tyre stocks rubber prices", { peers: ["MRF.NS", "APOLLOTYRE.NS", "CEATLTD.NS", "BALKRISIND.NS", "JKTYRE.NS"] }),
  batteries: P("Batteries / EV ecosystem", /batter|exide|amara raja|electric vehicle/i, { },
    ["EV adoption, storage demand", "Falling lithium prices", "Local manufacturing incentives"],
    ["Battery oversupply, EV slowdown", "Lithium spike, technology substitution", "Subsidies removed"],
    ["EV penetration", "Lithium price"], "EV battery", { peers: ["EXIDEIND.NS", "ARE&M.NS", "HBLENGINE.NS"] }),
  fmcg: P("Consumer staples / FMCG", /packaged foods|household|personal products|beverages|tobacco|food distribution|farm products|confectioners/i, { crude: -1 },
    ["Rural income recovery / good monsoon", "Commodity deflation (palm oil, crude, packaging)", "Premiumisation, wage growth"],
    ["Commodity inflation", "Weak rural demand, downtrading", "Competition, higher ad spend"],
    ["Volume growth", "Gross margin", "Rural growth"], "FMCG demand", { peers: ["HINDUNILVR.NS", "ITC.NS", "NESTLEIND.NS", "BRITANNIA.NS", "DABUR.NS"] }),
  sugar: P("Sugar / ethanol", /sugar|ethanol/i, { sugar: 1, crude: 1 },
    ["Sugar & ethanol prices rise", "Export quotas, lower inventories", "Government support (ethanol blending)"],
    ["Sugar glut, export restrictions", "Higher cane prices (FRP)", "Ethanol policy changes"],
    ["Sugar price", "Ethanol volumes", "Cane FRP"], "sugar prices ethanol", { peers: ["BALRAMCHIN.NS", "EIDPARRY.NS", "TRIVENI.NS", "RENUKA.NS", "DHAMPURSUG.NS"] }),
  durables: P("Consumer durables", /furnishings|appliances|consumer electronics|home improvement|household appliances|cables|wires/i, { rates: -1, copper: -1, steel: -1 },
    ["Rate cuts, easy consumer credit", "Housing construction, heat waves (ACs)", "Premiumisation, rural recovery"],
    ["Rate hikes, weak housing", "Commodity (copper/steel) inflation", "Inventory build-up"],
    ["Volume growth", "Gross margin"], "consumer durables demand", { peers: ["HAVELLS.NS", "VOLTAS.NS", "BLUESTARCO.NS", "WHIRLPOOL.NS", "CROMPTON.NS"] }),
  qsr: P("QSR / restaurants", /restaurants/i, { },
    ["Same-store sales growth (SSSG)", "Food inflation moderates, operating leverage", "Delivery growth, new-store economics"],
    ["Weak SSSG, discounting", "Food / wage / rent inflation", "Delivery commissions, cannibalisation"],
    ["SSSG", "ADS", "Store adds"], "QSR SSSG", { peers: ["JUBLFOOD.NS", "WESTLIFE.NS", "DEVYANI.NS", "SAPPHIRE.NS"] }),
  retail: P("Retail", /retail|department stores|apparel stores|internet retail/i, { rates: -1 },
    ["Wage growth, consumer confidence", "Same-store sales, festival season", "Store expansion, inventory efficiency"],
    ["Weak consumption, discounting", "Inventory build-up, rent inflation", "E-commerce disruption"],
    ["SSSG", "Revenue / sq ft", "Store adds"], "retail consumption", { peers: ["TRENT.NS", "DMART.NS", "ABFRL.NS", "SHOPERSTOP.NS", "VMART.NS"] }),
  real_estate: P("Real estate", /real estate|realty|reit/i, { rates: -1 },
    ["Mortgage-rate cuts", "Pre-sales acceleration, new launches", "Housing shortage, lower construction costs"],
    ["Rate hikes", "Unsold inventory, affordability deterioration", "Construction inflation, liquidity crisis"],
    ["Pre-sales", "Collections", "Unsold inventory"], "real estate housing sales", { peers: ["DLF.NS", "GODREJPROP.NS", "OBEROIRLTY.NS", "PRESTIGE.NS", "PHOENIXLTD.NS"] }),
  defence: P("Defence", /aerospace & defense|defence|defense/i, { },
    ["Defence budget, geopolitical tensions", "Indigenisation / import substitution", "Export orders, new contracts"],
    ["Procurement delays, budget cuts", "Order cancellations, execution problems"],
    ["Order book", "Order inflow", "Exports"], "defence stocks orders", { peers: ["BEL.NS", "HAL.NS", "BEML.NS", "BDL.NS", "MAZDOCK.NS"] }),
  railways: P("Railways", /railroad|railway|\brail\b|wagon|ircon|rvnl|irctc|irfc|titagarh|texmaco/i, { },
    ["Railway capex & budget", "Electrification, Vande Bharat, freight corridors", "Wagon & signalling orders"],
    ["Budget cuts, tender delays", "Order execution problems"],
    ["Railway capex", "Order inflow"], "railway capex", { peers: ["RVNL.NS", "IRCON.NS", "TITAGARH.NS", "TEXRAIL.NS", "IRCTC.NS"] }),
  airlines: P("Airlines", /airlines/i, { crude: -1, inr: -1 },
    ["Passenger growth, higher yields", "Lower ATF (crude)", "Rupee appreciation, capacity rationalisation"],
    ["ATF spike", "INR depreciation", "Price wars, aircraft groundings"],
    ["Passenger traffic", "Yield", "ATF price"], "airline ATF passenger traffic", { peers: ["INDIGO.NS"] }),
  airports: P("Airports", /airports|air services/i, { },
    ["Passenger growth, higher aero charges", "Retail / duty-free / non-aero revenue"],
    ["Traffic slowdown, regulatory restrictions", "Capex overruns"],
    ["Passenger traffic", "Non-aero revenue"], "airport traffic", { peers: ["GMRAIRPORT.NS"] }),
  shipping: P("Shipping / ports / logistics", /marine shipping|shipping|ports|freight|logistics|trucking|integrated freight/i, { china: 1, crude: -1 },
    ["Freight rates up (Baltic Dry, container)", "Canal / strait disruptions, port congestion", "Trade growth, GST formalisation"],
    ["Global recession, freight rate collapse", "New vessel supply", "Fuel costs"],
    ["Freight rates", "Volumes", "Utilisation"], "freight rates shipping", { peers: ["CONCOR.NS", "ADANIPORTS.NS", "GESHIP.NS", "SCI.NS", "BLUEDART.NS"] }),
  pharma: P("Pharmaceuticals", /drug manufacturers|pharma|biotech/i, { inr: 1 },
    ["USFDA approvals, drug shortages", "US generic pricing stabilisation", "Specialty launches", "INR depreciation"],
    ["USFDA warning letters / import alerts", "Generic price erosion", "Patent expiries, recalls", "US healthcare reform"],
    ["US revenue", "ANDA approvals", "R&D / sales"], "pharma USFDA", { index: { symbol: "^CNXPHARMA", name: "NIFTY Pharma" } }),
  hospitals: P("Hospitals / healthcare services", /medical care|hospital|healthcare facilities|medical instruments/i, { },
    ["Occupancy & ARPOB up", "Medical tourism, insurance penetration", "New beds, better case mix"],
    ["Occupancy decline, pricing restrictions", "Doctor shortages, cost inflation", "Capacity oversupply"],
    ["Occupancy", "ARPOB", "Bed additions"], "hospital stocks", { peers: ["APOLLOHOSP.NS", "FORTIS.NS", "NH.NS", "MAXHEALTH.NS"] }),
  diagnostics: P("Diagnostics", /diagnostics/i, { },
    ["Preventive healthcare, volume growth", "Consolidation, pricing power"],
    ["Price competition, hospital-owned labs", "Volume slowdown"],
    ["Patient volumes", "Realisation / test"], "diagnostics", { peers: ["LALPATHLAB.NS", "METROPOLIS.NS", "THYROCARE.NS"] }),
  textiles: P("Textiles & apparel", /textile|apparel manufacturing|footwear/i, { cotton: -1, inr: 1 },
    ["Cotton prices fall, yarn prices rise", "Export demand (US/EU), China+1", "INR depreciation"],
    ["Cotton spike", "Weak global demand, inventory build-up", "China competition, freight costs"],
    ["Cotton price", "Export orders"], "textile exports cotton", { peers: ["PAGEIND.NS", "ARVIND.NS", "WELSPUNLIV.NS", "TRIDENT.NS", "KPRMILL.NS"] }),
  jewellery: P("Jewellery / luxury", /luxury|jewel|titan|kalyan|senco/i, { gold: 1 },
    ["Wedding season, income growth", "Organised-market share gains", "Higher gold lifts nominal sales"],
    ["Gold prices prohibitively high", "Consumer slowdown, import restrictions"],
    ["SSSG", "Gold price"], "gold price jewellery demand", { peers: ["TITAN.NS", "KALYANKJIL.NS", "SENCO.NS", "RAJESHEXPO.NS"] }),
  ems: P("Electronics / EMS / semis", /electronic components|electronics|semiconductor|scientific & technical/i, { inr: -1, semis: 1, ai_dc: 1 },
    ["China+1, PLI incentives", "Smartphone exports, import substitution", "Semiconductor upcycle, AI demand"],
    ["PLI reduction, customer concentration", "Component shortages", "Global electronics slowdown, export controls"],
    ["Order book", "Exports", "Margins"], "electronics manufacturing PLI", { peers: ["DIXON.NS", "AMBER.NS", "KAYNES.NS", "SYRMA.NS"] }),
  internet: P("Internet / platforms / fintech", /internet|fintech|payments|online|paytm|one 97|pb fintech|zomato|eternal|nykaa|fsn e-commerce|swiggy/i, { rates: -1, smallcap: 1 },
    ["GMV & take-rate growth, ad revenue", "Path to profitability", "Lower CAC, monetisation"],
    ["Cash burn, discounting, competition", "Regulatory intervention (RBI / payments)", "Higher rates hit long-duration valuations"],
    ["GMV", "Take rate", "Contribution margin"], "internet stocks", { peers: ["NAUKRI.NS", "INDIAMART.NS", "JUSTDIAL.NS", "PAYTM.NS", "POLICYBZR.NS"] }),
  media: P("Media / entertainment", /entertainment|broadcasting|publishing|advertising|gaming/i, { },
    ["Advertising cycle, subscriptions", "Sports rights / content wins"],
    ["Ad recession, OTT competition", "Content costs, regulation (gaming)"],
    ["Ad revenue", "Subscribers"], "media stocks advertising", { peers: ["SUNTV.NS", "ZEEL.NS", "PVRINOX.NS", "NETWORK18.NS"] }),
  hotels: P("Hotels / tourism", /lodging|resorts|travel services|leisure|hotel/i, { },
    ["Occupancy & ADR up", "Weddings, business travel, tourism"],
    ["Recession, travel restrictions", "New hotel supply, geopolitical shocks"],
    ["Occupancy", "ADR", "RevPAR"], "hotel occupancy", { peers: ["INDHOTEL.NS", "EIHOTEL.NS", "LEMONTREE.NS", "CHALET.NS"] }),
  education: P("Education", /education/i, { },
    ["Enrolment growth, government contracts", "Online adoption, premiumisation"],
    ["Regulatory restrictions, lower enrolments", "Pricing pressure"],
    ["Enrolments", "Revenue per student"], "education stocks", { peers: ["NIITLTD.NS", "APTECHT.NS"] }),
};

const GENERIC = P("General", /.^/, {},
  ["Earnings upgrades / strong results", "Order wins, capacity expansion", "Favourable policy, sector tailwinds", "Liquidity / FII inflows, index inclusion"],
  ["Earnings downgrades / weak results", "Regulatory action, governance issues", "Input-cost spikes", "Liquidity outflows, promoter selling"],
  ["Revenue growth", "EBITDA margin", "Order book"], "");

/** Pick the playbook for a company from Yahoo sector / industry and its name. */
export function playbookFor(sector = "", industry = "", name = "") {
  const texts = [name, industry, sector].map((t) => (t || "").toLowerCase());
  // Name-specific playbooks (paints, railways, jewellery, microfinance…) win over generic industry ones.
  const nameFirst = ["paints", "railways", "jewellery", "microfinance", "batteries", "sugar", "aluminium", "internet"];
  for (const k of nameFirst) if (PLAYBOOKS[k].match.test(texts[0])) return { key: k, ...PLAYBOOKS[k] };
  for (const t of texts.slice(1)) {
    if (!t) continue;
    for (const [k, p] of Object.entries(PLAYBOOKS)) if (p.match.test(t)) return { key: k, ...p };
  }
  return { key: "general", ...GENERIC };
}

/* ---------- cross-industry macro triggers (from the trigger map) ---------- */

export const MACRO_TRIGGERS = [
  { name: "RBI rate cut / falling yields", factor: "rates", dir: -1, winners: "Banks, NBFCs, real estate, autos, durables, capital goods, utilities, infra", losers: "Banks with slow deposit repricing" },
  { name: "Rate hike / rising yields", factor: "rates", dir: 1, winners: "Deposit-rich banks, cash-rich companies", losers: "Real estate, autos, durables, NBFCs, leveraged & long-duration stocks" },
  { name: "INR depreciation", factor: "inr", dir: 1, winners: "IT, pharma, textiles, specialty chemicals, auto-component exporters", losers: "Airlines, oil importers, electronics importers, USD borrowers" },
  { name: "Crude oil spike", factor: "crude", dir: 1, winners: "Upstream oil, coal, gas substitutes", losers: "Airlines, paints, tyres, chemicals, logistics, FMCG, OMCs" },
  { name: "Crude oil collapse", factor: "crude", dir: -1, winners: "India macro (trade balance, inflation), consumers, airlines, paints, OMCs", losers: "Upstream oil" },
  { name: "Strong US dollar", factor: "usd", dir: 1, winners: "Exporters (IT, pharma, textiles)", losers: "Importers, EM risk appetite overall" },
  { name: "China stimulus", factor: "china", dir: 1, winners: "Metals, shipping, commodities", losers: "Can raise Chinese exports that hurt Indian steel / chemicals" },
  { name: "US equity sell-off / recession risk", factor: "spx", dir: -1, winners: "Defensive FMCG, utilities, healthcare", losers: "IT, textiles, chemicals, auto components, metals" },
  { name: "Risk-off / VIX spike", factor: "vix", dir: 1, winners: "Gold, defensives", losers: "Small caps, high-beta cyclicals" },
  { name: "AI capex boom / slowdown", factor: "ai_dc", dir: -1, winners: "—", losers: "AI-linked power equipment, transformers, cables, EMS, data-centre plays, IT services" },
  { name: "Liquidity expansion (mid/small caps rally)", factor: "smallcap", dir: 1, winners: "Small/mid caps, financials, capital goods, IPOs", losers: "—" },
];
